/** @type {import('prettier').Config} */
module.exports = {
  arrowParens: "always",
  printWidth: 80,
  singleQuote: false,
  semi: true,
  trailingComma: "all",
  tabWidth: 2,
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  importOrder: [
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/(.*)$",
    "^@/helpers(.*)$",
    "^@/installers/(.*)$",
    "^@/utils/(.*)$",
    "",
    "^[./]",
  ],
  plugins: [require("@ianvs/prettier-plugin-sort-imports")],
};
