import type { Session } from "@acme/auth";
import type PrismaTypes from "@pothos/plugin-prisma/generated";
import type { NextApiRequest, NextApiResponse } from "next";

import { prisma } from "@acme/database";
import SchemaBuilder from "@pothos/core";
import ScopeAuthPlugin from "@pothos/plugin-scope-auth";
import PrismaPlugin from "@pothos/plugin-prisma";
import { DateTimeResolver } from "graphql-scalars";

/**
 * This is where all the GraphQL stuff for Pothos is created and configured. This file documents
 * many possible permutations of features you might want to have on your GraphQL API.
 * @see: https://pothos-graphql.dev/docs/guide/schema-builder
 */

/**
 * We check for the NODE_ENV to allow re-registration of plugins in development mode. This is used to
 * bypass Next.js behavior that triggers the error `Received multiple implementations for plugin {pluginName}`
 * @see: https://github.com/hayes/pothos/issues/696
 * */
const isDevelopment = process.env.NODE_ENV === "development";

if (isDevelopment) {
  SchemaBuilder.allowPluginReRegistration = true;
}

export const builder = new SchemaBuilder<{
  /** AUTHORIZATION
   *
   * This property defines the authorization scopes present on your GraphQL. You can one or multiple
   * authorization roles, and define them based on roles or permission access from your business logic.
   * @see: https://pothos-graphql.dev/docs/plugins/scope-auth
   */
  AuthScopes: {
    authorizedUser: boolean;
  };
  /** PRISMA INTEGRATION
   *
   * This property defines the PrismaTypes that are generated by the Prisma Client specifically for
   * Pothos. This will allow you to access your database queries in a typesafe way.
   * @see: https://pothos-graphql.dev/docs/plugins/prisma
   */
  PrismaTypes: PrismaTypes;

  /** CONTEXT
   *
   * This property defines the contexts that are available in the API, and are sent from the client with each
   * new request. Populating the context allows you to access relevant things when precessing the request,
   * such as session information.
   * @see: https://pothos-graphql.dev/docs/guide/context
   */
  Context: {
    req: NextApiRequest;
    res: NextApiResponse;
    session: Session | null;
  };

  /** SCALARS
   *
   * Here you can inject custom GraphQL scalars to suit your needs. In this instance, we use the common
   * `DateTime` scalar as an example. Later in this file, we also register the custom scalar to the schema.
   * @see: https://pothos-graphql.dev/docs/guide/scalars
   */
  Scalars: {
    DateTime: {
      Input: Date;
      Output: Date;
    };
  };
}>({
  /**
   * This is where you will register some of the Pothos plugins you configured earlier.
   * Check the docs to see other available plugins.
   * @see: https://pothos-graphql.dev/docs/plugins
   *
   * When using scope-auth with other plugins, always make sure that the scope-auth plugin is registered first.
   * @see: https://pothos-graphql.dev/docs/plugins/scope-auth#important
   */
  plugins: [ScopeAuthPlugin, PrismaPlugin],

  /** This option configures how the authScopes you defined earlier are resolved.
   * In this example, we use information from the request's context to see if the user
   * is authorized.
   *
   * @see: https://pothos-graphql.dev/docs/plugins/scope-auth
   */
  authScopes: async (context) => ({
    authorizedUser: context.session ? true : false,
  }),
  prisma: {
    client: prisma,
  },
});

/**
 * Register the root types of the schema. This is required to be able to use the `queryType` and `mutationType`
 * on all other files inside the `schema` folder.
 * */
builder.queryType();
builder.mutationType();

/**
 * Register custom scalars here. The scalars registered here can be used to define fields on the schema entities.
 * @see: https://pothos-graphql.dev/docs/guide/scalars#scalars
 * */
builder.addScalarType("DateTime", DateTimeResolver, {});
